<a href="https://colab.research.google.com/github/maschu09/colab-test/blob/main/myfirstnotebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello world!")

Hello world!


# My very first Colab notebook

Testing various features starting with "Hello world!".
Try out _various_ __formatting__ `options`!
* list item 1
* list item 2

## Sub heading

Author: Martin Schultz, February 2025


In [2]:
import numpy as np
from sklearn.ensemble import RandomForestClassifier
# training data
X = np.array([[[0.4,0.3,0.3],[0.6,0.5,0.3],[0.7,0.4,0.4]],[[0.4,0.4,0.3],[0.4,0.3,0.3],[0.7,0.5,0.4]],[[0.0,0.6,0.3],[0.0,0.5,0.2],[0.6,0.4,0.3]]])
X = np.reshape(X, (9,3))
# labels
y = np.array([[1, 1, 1],[0, 1,1],[0,0,1]])
y = y.flatten()   # similar to np.reshape(y, (9,))
# initiate and train classifier
clf = RandomForestClassifier(random_state=0)
clf.fit(X,y)
# print class predictions of the training data
print(clf.predict(X))

[1 1 1 0 1 1 0 0 1]


In [ ]:
test = [[r,0.6,0.3] for r in np.arange(0.,1.,0.05)]
print(clf.predict(test))

[0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1]


In [5]:
test = [[0.4,g,0.] for g in np.arange(0.,1.,0.05)]
print(clf.predict(test))

[1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0]
